language: c

script:
    - ./remake ms.pdf

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
    - ./travis-tool.sh install_github richfitz/storr
    - ./travis-tool.sh install_github richfitz/remake
    - Rscript -e 'remake::install_remake(".")'

install:
    - Rscript -e 'options(repos="http://cran.rstudio.com"); remake::install_missing_packages()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack: bdkd:DPfom03G2FgVC9z69XMi9g4L
