language: c

sudo: required

script:
    - ./remake ms.pdf

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
    # See plant/.travis.yml: this updates g++ to be C++11 capable.
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
    - sudo apt-get -qq install g++-4.9 libgfortran3-dbg
    - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/x86_64-linux-gnu/libgfortran.so
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
    # Then continue with the installation:
    - ./travis-tool.sh install_github richfitz/storr
    - ./travis-tool.sh install_github richfitz/remake
    - Rscript -e 'remake::install_remake(".")'

install:
    - Rscript -e 'options(repos="http://cran.rstudio.com"); remake::install_missing_packages()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack: bdkd:DPfom03G2FgVC9z69XMi9g4L
